/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class discretasjni_lib_JavaDiscretas */

#ifndef _Included_discretasjni_lib_JavaDiscretas
#define _Included_discretasjni_lib_JavaDiscretas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     discretasjni_lib_JavaDiscretas
 * Method:    union
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_discretasjni_lib_JavaDiscretas_union
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     discretasjni_lib_JavaDiscretas
 * Method:    interseccion
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_discretasjni_lib_JavaDiscretas_interseccion
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     discretasjni_lib_JavaDiscretas
 * Method:    diferencia
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_discretasjni_lib_JavaDiscretas_diferencia
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     discretasjni_lib_JavaDiscretas
 * Method:    diferenciaSimetrica
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_discretasjni_lib_JavaDiscretas_diferenciaSimetrica
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     discretasjni_lib_JavaDiscretas
 * Method:    complemento
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_discretasjni_lib_JavaDiscretas_complemento
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
